# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule:
    - cron: '00 */3 * * *'
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches: [ master, main ]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SVG metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: jaotan
          template: classic
          base: header, activity, community
          config_timezone: Asia/Tokyo
          repositories_affiliations: owner, collaborator, organization_member
          
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes
